ethereum/snake-charmers-tactical-manual

- style-guide.md
Otherwise triggers flake8 E125
> Double-indent arguments in function definition

- git-and-github.md
I've found this super helpful. Is it worth recommending this as a team practice?
> Suggested template for new repositories

- style-guide.md
Just fixing an unclosed code block.
> Fix unclosed code formatting

- testing.md
Adapted from https://github.com/ethpm/py-ethpm/pull/51#issuecomment-402350408
> More background on why mocks are problematic

- opsec.md
> Add note about why SMS is not secure

- style-guide.md
As a follow up to https://github.com/ethereum/py-evm/pull/1390#discussion_r224931867, this adds a section on typing and how to choose between types for function parameters and return values.
> Add section on how to choose between types

- documentation.md
> Docs about how to write docs

- README.md
- cutting-a-release.md
Forgot the push to master step originally. Also added link to the readme.
> Add link to release file in README

- style-guide.md
Spawned from [this comment](https://github.com/ethereum/trinity/pull/129#discussion_r247182154)
> Add a note on naming booleans

- style-guide.md
> Add recommendations for docstring style

- testing.md
This happens to me once in a blue moon, and I usually forget the details of what to do between recurrance.
> Tips for tracking down segmentation faults

- documentation.md
Just a few edits to improve flow in the documentation article.
> Flow edits in documentation article

- git-and-github.md
Every time I set up a new machine I have to google the syntax of this again and again so I thought it is worth adding it to our tips and tricks section.
> Add tip about fetchint PRs

- testing.md
A series of steps is provided to try and refactor an implementation away from
one that seems to be most easily tested with mocking.
> Suggest refactoring to avoid mocking

- testing.md
As per a discussion on discord, this PR adds a section on suggested test suite structure.  Also fixes a couple of other random things.
> Add section on test suite structure

- template.md
https://github.com/ethereum/ethereum-python-project-template/pull/77 converted the filler scripts from bash to python. This pr updates the usage instructions.
> project template filler scripts converted from bash to python

- cutting-a-release.md
Our release process has changed a fair amount in 4 years :)
> Update release doc

- cutting-a-release.md
Just added a few bullets to `cutting-a-release.md`. Let me know if I missed anything or if anything else should be added!
> Update release docs

- cutting-a-release.md
Just added a step to put release in the announcements channel so it's queued up for a tweet.
> Add announcements channel step

- cutting-a-release.md
Thought these would be handy in the future.
> Add beta release commands
